-- V6: منصة متعددة الدعوات
create table if not exists public.invitations (
  id bigint generated by default as identity primary key,
  slug text unique not null,
  groom text not null default '',
  bride text not null default '',
  dateText text not null default '',
  timeText text not null default '',
  venue text not null default '',
  address text not null default '',
  mapsUrl text not null default '',
  countdown text not null default '',
  message text not null default '',
  music text not null default '',
  musicVolume numeric not null default 0.45,
  rsvpPhone text not null default '',
  published boolean not null default false,
  updated_at timestamptz not null default now()
);
alter table public.invitations enable row level security;

create policy "public can read published invitations"
on public.invitations for select to anon, authenticated
using (published = true);

-- المصمم يستطيع رؤية/إدارة كل الدعوات.
-- غيّر EMAIL_HERE إلى بريد المصمم.
create policy "designer can manage invitations"
on public.invitations for all to authenticated
using ((select auth.jwt()->>'email') = 'EMAIL_HERE')
with check ((select auth.jwt()->>'email') = 'EMAIL_HERE');

-- إذا كان جدول invitations موجوداً من النسخة السابقة:
alter table public.invitations add column if not exists published boolean not null default false;
alter table public.invitations add column if not exists updated_at timestamptz not null default now();
